### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/epfl-enac-build-push-deploy-action#1]
- [x] add proper documentation on how to use and versions
- [x] Centralize version for all CD_TOKEN (one to rule them all)
- [ ] Have error handling for CURL (401 should return an exit 1 and have pipeline failed)
- [ ] Bonuse have trigger dispatch event check the status of the workflow running on eenack8s-app-config
- [ ] Use action.yml default to use local workflow via the following if possible
```
using: "composite"
  steps:
    - name: Call reusable workflow
      run: |
        gh workflow run .github/workflows/deploy-prod.yml --ref ${{ github.ref }}
```
